### PR TITLE
use ical as event source

### LINKED ISSUE #17: Calender with iCal
The embedded calendar could be fitted with an iCal-Import, where you can Import Nextcloud Calender's, to show it's entries.

### PR DESCRIPTION
**Pull request by jens1o**
supersedes #54 

fixes #17

### CODE REVIEW

**Comment by jens1o** [comment]
To run this on your local device, you need to have composer (like npm, just for PHP) installed and run `composer install` in the root directory.

**Comment by pascalwittler** [comment]
I have nothing against the integration of composer packages or libraries in general, but currently (for over a year) there is not even a reliable workflow for uploading some static files to the web server.

As long as the upload after changes here on Github is achieved by asking people you know and need to reach via chat or personal conversation to copy files by hand, I am against requiring further steps and installed software.

**Comment by jens1o** [comment]
see https://github.com/entropia/landing-page/pull/54#issuecomment-1850333516

**Review by soc — APPROVED** [review]

**Comment by jens1o** [comment]
this will (probably) be solved using MediaWiki :)

let's leave this for now

**Comment by pascalwittler** [comment]
"Project iCal" has been cancelled by @stirlingzero again

**Pull request closed without merging**
